#setwd("D:/Projects/mind")
#getting data from file
data <- read.csv("data.csv")

#selecting based on days
suns <- subset(data, Day == "Sun")
mons <- subset(data, Day == "Mon")
tues <- subset(data, Day == "Tue")
weds <- subset(data, Day == "Wed")
thurs <- subset(data, Day == "Thur")
fris <- subset(data, Day == "Fri")
sats <- subset(data, Day == "Sat")

ini <- c(1,2,3,4,5,6,7,8,9)
sun <- c()
mon <- c()
tue <- c()
wed <- c()
thur <- c()
fri <- c()
sat <- c()

#taking mean
for(i in ini)  {
	sun <- c(sun, mean(suns[,1+i]))
	mon <- c(mon, mean(mons[,1+i]))
	tue <- c(tue, mean(tues[,1+i]))
	wed <- c(wed, mean(weds[,1+i]))
	thur <- c(thur, mean(thurs[,1+i]))
	fri <- c(fri, mean(fris[,1+i]))
	sat <- c(sat, mean(sats[,1+i]))
}
x6 <- c(sun[1],mon[1],tue[1],wed[1],thur[1],fri[1],sat[1])
x8 <- c(sun[2],mon[2],tue[2],wed[2],thur[2],fri[2],sat[2])
x10 <- c(sun[3],mon[3],tue[3],wed[3],thur[3],fri[3],sat[3])
x12<- c(sun[4],mon[4],tue[4],wed[4],thur[4],fri[4],sat[4])
x14<- c(sun[5],mon[5],tue[5],wed[5],thur[5],fri[5],sat[5])
x16<- c(sun[6],mon[6],tue[6],wed[6],thur[6],fri[6],sat[6])
x18<- c(sun[7],mon[7],tue[7],wed[7],thur[7],fri[7],sat[7])
x20<- c(sun[8],mon[8],tue[8],wed[8],thur[8],fri[8],sat[8])
x22<- c(sun[9],mon[9],tue[9],wed[9],thur[9],fri[9],sat[9])
days <- c("Sun","Mon","Tues","Wed","Thur","Fri","Sat")

#Ploting the graphs
png(file = "at_6.png")
barplot(x6,names.arg = days, xlab = "Days", ylab = "Passengers", main = "At 6.00",col = 1)
dev.off()
png(file = "at_8.png")
barplot(x8,names.arg = days, xlab = "Days", ylab = "Passengers", main = "At 8.00",col = 2)
dev.off()
png(file = "at_10.png")
barplot(x10,names.arg = days, xlab = "Days", ylab = "Passengers", main = "At 10.00",col = 3)
dev.off()
png(file = "at_12.png")
barplot(x12,names.arg = days, xlab = "Days", ylab = "Passengers", main = "At 12.00",col = 4)
dev.off()
png(file = "at_14.png")
barplot(x14,names.arg = days, xlab = "Days", ylab = "Passengers", main = "At 14.00",col = 5)
dev.off()
png(file = "at_16.png")
barplot(x16,names.arg = days, xlab = "Days", ylab = "Passengers", main = "At 16.00",col = 6)
dev.off()
png(file = "at_18.png")
barplot(x18,names.arg = days, xlab = "Days", ylab = "Passengers", main = "At 18.00",col = 7)
dev.off()
png(file = "at_20.png")
barplot(x20,names.arg = days, xlab = "Days", ylab = "Passengers", main = "At 20.00",col = 8)
dev.off()
png(file = "at_22.png")
barplot(x22,names.arg = days, xlab = "Days", ylab = "Passengers", main = "At 22.00",col = 9)
dev.off()

#Writing data into csv file
combine <- matrix(c(sun,mon,tue,wed,thur,fri,sat),nrow=9)
write.csv(combine,"output.csv")

