combine <- matrix(c(sunmean,monmean,tuemean,wedmean,thurmean,frimean,satmean),nrow=9)
write.csv(combine,file="Weighted Mean.csv")
data <- read.csv("Weighted Mean.csv")
suns <- data[,2]
mons <- data[,3]
tues <- data[,4]
weds <- data[,5]
thurs <- data[,6]
fris <- data[,7]
sats <- data[,8]
new <- read.csv("weekly.csv")
suns <- matrix(c(suns,new[,1]),nrow=9)
mons <- matrix(c(mons,new[,2]),nrow=9)
tues <- matrix(c(tues,new[,3]),nrow=9)
weds <- matrix(c(weds,new[,4]),nrow=9)
thurs <- matrix(c(thurs,new[,5]),nrow=9)
fris <- matrix(c(fris,new[,6]),nrow=9)
sats <- matrix(c(sats,new[,7]),nrow=9)
w <- c(60,40)

sunmean <- vector(,length=9)
for(i in 1:9)
	sunmean[i] <- weighted.mean(suns[i,],w)
png(file = graphs[1])
plot(sunmean,type="o", xlab ="Hour", ylab = "Number of Passengers",main = "weighted mean" )
axis(1,at=1:9,labels=c(6,8,10,12,14,16,18,20,22))
dev.off()

monmean <- vector(,length = 9)
for(i in 1:9)
	monmean[i] <- weighted.mean(mons[i,],w)
png(file = graphs[2])
plot(monmean,type="o", xlab ="Hour", ylab = "Number of Passengers",main = "weighted mean" )
axis(1,at=1:9,labels=c(6,8,10,12,14,16,18,20,22))
dev.off()
predict.function(monmean)

tuemean <- vector(, length=9)
for(i in 1:9)
	tuemean[i] <- weighted.mean(tues[i,],w)
png(file = graphs[3])
plot(sunmean,type="o", xlab ="Hour", ylab = "Number of Passengers",main = "weighted mean" )
axis(1,at=1:9,labels=c(6,8,10,12,14,16,18,20,22))
dev.off()
predict.function(tuemean)

wedmean <- vector(,length = 9)
for(i in 1:9)
	wedmean[i] <- weighted.mean(weds[i,],w)
png(file = graphs[4])
plot(wedmean,type="o", xlab ="Hour", ylab = "Number of Passengers",main = "weighted mean" )
axis(1,at=1:9,labels=c(6,8,10,12,14,16,18,20,22))
dev.off()
predict.function(wedmean)

thurmean <- vector(,length = 9)
for(i in 1:9)
	thurmean[i] <- weighted.mean(thurs[i,],w)
png(file = graphs[5])
plot(thurmean,type="o", xlab ="Hour", ylab = "Number of Passengers",main = "weighted mean" )
axis(1,at=1:9,labels=c(6,8,10,12,14,16,18,20,22))
dev.off()
predict.function(thurmean)

frimean <- vector(,length = 9)
for(i in 1:9)
	frimean[i] <- weighted.mean(fris[i,],w)
png(file = graphs[6])
plot(frimean,type="o", xlab ="Hour", ylab = "Number of Passengers",main = "weighted mean" )
axis(1,at=1:9,labels=c(6,8,10,12,14,16,18,20,22))
dev.off()
predict.function(frimean)

satmean <- vector(,length = 9)
for(i in 1:9)
	satmean[i] <- weighted.mean(sats[i,],w)
predict.function(satmean)
png(file = graphs[7])
plot(satmean,type="o", xlab ="Hour", ylab = "Number of Passengers",main = "weighted mean" )
axis(1,at=1:9,labels=c(6,8,10,12,14,16,18,20,22))
dev.off()
combine <- matrix(c(sunmean,monmean,tuemean,wedmean,thurmean,frimean,satmean),nrow=9)
write.csv(combine,file="Weighted Mean.csv")